FROM ruby:2.4.1-alpine3.4

ENV BUNDLE_JOBS=2
ENV APP_ROOT /app


RUN mkdir -p $APP_ROOT
WORKDIR $APP_ROOT

RUN apk update && \
    apk --update add --virtual build-dependencies \
                     build-base \
                     ruby-dev \
                     openssl-dev \
                     postgresql-dev \
                     libc-dev \
                     linux-headers && \
    apk --update add ruby \
                     ruby-irb \
                     ruby-json \
                     ruby-rake \
                     ruby-bigdecimal \
                     ruby-io-console \
                     libstdc++ \
                     tzdata \
                     postgresql-client \
                     git

RUN echo -e 'http://dl-cdn.alpinelinux.org/alpine/edge/main\nhttp://dl-cdn.alpinelinux.org/alpine/edge/community\nhttp://dl-cdn.alpinelinux.org/alpine/edge/testing' > /etc/apk/repositories && \
    apk add --no-cache yarn


COPY Gemfile $APP_ROOT
COPY Gemfile.lock $APP_ROOT
COPY yarn.lock $APP_ROOT
COPY package.json $APP_ROOT

RUN bundle install
RUN yarn install

RUN apk del build-dependencies

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
